[package]
name = "a3s-science-registry-builder"
version = "0.1.0"
edition = "2021"
publish = false
default-run = "a3s-science-registry-builder"

[dependencies]
a3s-use-core = { git = "https://github.com/A3S-Lab/Use", rev = "01c93ee359f00e5d4561fbb4df00f0f70e68e640" }
a3s-use-extension = { git = "https://github.com/A3S-Lab/Use", rev = "01c93ee359f00e5d4561fbb4df00f0f70e68e640" }
anyhow = "1"
flate2 = "1"
olpc-cjson = "0.1"
ring = "0.17"
semver = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
tar = "0.4"
tempfile = "3"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
